enum SidebarItem {
  dashboard,
  userManagement,
  geographicalAreas,
  motherStations,
  daughterBoosterStations,
  routeManagement,
  lcvManagement,
  dbsStockStatus,
  lcvSchedules,
  lcvTripStatus,
  dryOutHistory,
  msWiseLcvQueue,
  salesHistory,
  Reports,
  map,
  settings,
}
